### PR TITLE
Might solve mac error

### PR DESCRIPTION
**Pull request by ofgulban**
The error in macs (#3 ) might be due to pyplot import. I have changed this. Cannot test it though because I dont have a mac :)

### CODE REVIEW

**Comment by miykael** [comment]
I've merged it. @ilkayisik - can you test if this takes care of the issue?

**Comment by ilkayisik** [comment]
I have tested it. Looks like it solved the issue :) Thanks @ofgulban, thanks @miykael !
you might need another mac user to test it tho to make sure.

**Comment by miykael** [comment]
Cool, thanks for testing and thanks for the fix!

**Comment by ofgulban** [comment]
Solved until some _mac user_ complains :D

**Pull request merged**
